### ISSUE TITLE
This still work?

### ISSUE THREAD

**Issue by ssamachi** [hoangvu12/discord-storage#1]
^

**Comment by hoangvu12** [comment]
It should works fine :)

**Comment by ssamachi** [comment]
> It should works fine :)

Hi, it's uploading but in console it's saying no attachments found. I use url for image testing.

**Comment by ssamachi** [comment]
> It should works fine :)

but it's saying No attachments found. But the image is getting uploaded on mi server. I need the response to get the image link when uploaded. And when I print data from the axios.post it's a bunch of random characters

**Comment by hoangvu12** [comment]
> > It should works fine :)
> 
> but it's saying No attachments found. But the image is getting uploaded on mi server. I need the response to get the image link when uploaded. And when I print data from the axios.post it's a bunch of random characters

![image](https://user-images.githubusercontent.com/68330291/205554875-e43d6f39-642e-4864-aa4e-33b8f08c626f.png)

It works fine on my local.

**Comment by ssamachi** [comment]
> 

Can you try using image link? Thank you for your response

**Comment by ssamachi** [comment]
> > 
> 
> Can you try using image link? Thank you for your response

I made it work now. thank you so much

**Comment by ssamachi** [comment]
> 

@hoangvu12 i found the issue it was because I was using axios 1.2.0.
